### ISSUE TITLE
volgorde headings

### ISSUE THREAD

**Issue by tom-2810** [KaanKalmi/your-tribe-profile-card#1]
<img width="926" alt="Screenshot 2023-09-15 at 10 23 18" src="https://github.com/KaanKalmi/your-tribe-profile-card/assets/112861614/eac28d06-b3fa-4813-a87d-8028993f5f85">

Kijk eens naar de web developer chrome extension. Daarmee kan je de heading semantic checken. En dus de volgorde van je html document.

https://github.com/KaanKalmi/your-tribe-profile-card/blob/35ad86ba04c4c23148a4dc9376558ba456bee577/index.html#L24

**Comment by KaanKalmi** [comment]
Gefixt
